### PR TITLE
[Next] WebIO v1.0

### PR DESCRIPTION
**Pull request by travigd**
See #368

### CODE REVIEW

**Comment by shashi** [comment]
Separate PR for each feature?

**Comment by travigd** [comment]
> Separate PR for each feature?

Yeah I was planning on that to make things manageable while still keeping master usable if we need to make other changes.

**Comment by aminya** [comment]
This seems like a huge PR. 😄. 

I want to add some features from WebIO into my package [AcuteML](https://github.com/aminya/AcuteML.jl/issues/33). Things like "External frontend interfaces" and "JavaScript interface" can be used for AcuteML too.

I should observe this PR to see what changes.

**Comment by shashi** [comment]
> Yeah I was planning on that to make things manageable while still keeping master usable if we need to make other changes.

Yes please!

**Pull request closed without merging**
