### PR TITLE
Proposal: new `node()` vararg constructor

### LINKED ISSUE #156: WebIO does strange things and crashes when trying to render images
I've tried:

```julia
using TestImages, WebIO

testimage("cameraman") |> dom"div"
```

and the jupyter notebook more or less crashed while Juno survived and said that the result was a `Node` with `263144` descendants. Not sure what's going wrong but we definitely need to figure out image rendering.

### PR DESCRIPTION
**Pull request by rdeits**
This implements the suggestion I made in #156 (and fixes #156 ). 

It's kind of obnoxious to ask users to switch from `Node()` to `node()` in their code, so I'm open to other suggestions. 

For example, instead of doing this, we could keep the vararg `Node()` constructor as-is and replace all our internal usage with a new `_node_internal()` constructor that takes an `AbstractVector` of children. 

But in either case, I think we should be sure that the user-facing constructor has *only* the vararg method, rather than having the ambiguous vararg and Vector methods.

### CODE REVIEW

**Comment by piever** [comment]
I'd actually prefer to have a `node` function. I've added one in Widgets already and I think this PR could extend that placeholder (this way people can use it without depending on WebIO when defining Interact recipes).
I would also like to be less strict about the tag and accept strings (i.e. `node("div", ...)`) if that doesn't create conflicts.

We also need to be careful what `n(v)` does when `n` is a `Node` and `v` a vector.

**Comment by piever** [comment]
Regarding the switch to `node`, I think it's not too bad of in conjunction with the Julia 0.7 upgrade: People will be upgrading anyway and this one can be done with a simple Ctrl+ Shift+F or some at equivalent command on most editors I suppose.

**Comment by shashi** [comment]
I like this change. It's a good solution for #156 although it would take 2 releases to fix. I think the deprecation you have added should serve OK in getting people to move to `node`. Better to do this now than later.

**Comment by rdeits** [comment]
Ok, will do. I'm just adding a few more tests

**Comment by rdeits** [comment]
@piever you mentioned having this `node()` function extend the one in Widgets.jl, but WebIO doesn't currently depend on Widgets. Do you want me to add that dependency?

**Comment by piever** [comment]
Yes, that'd be ideal. The dependency is very lightweight and Widgets is already 0.7 compatible. Also, I hope the `node(s::AbstractStirng, args...; kwargs...) = node(Symbol(s), args...; kwargs...)` is not a problem to have in WebIO. In Widgets the macros by default replace symbols with subwidgets (like StatPlots, DataFramesMeta or JuliaDBMeta) so it's quite useful to be able to call this function with a string instead.

**Comment by rdeits** [comment]
Ok, I've extended `Widgets.node()` and added a `::AbstractString` method to `promote_instanceof()`, so you can do `node(::AbstractString, children...)` and get the same result as `node(::Symbol, children...)`.

**Comment by rdeits** [comment]
Ah, I just realized that extending `Widgets.node()` in this way might not be a good idea, as it's definitely type-piracy...

**Comment by piever** [comment]
It is type-piracy, but it's the default strategy with low dependency packages. Plots does the same: the function `plot` is defined in RecipesBase and Plots extends it (and we do the same for `Observable`: the `show` method for `Observable` is defined here but WebIO doesn't "possess" neither `Observable` nor `show`). The only caveat is to be careful that WebIO is the package to define general methods for `node`.

**Comment by rdeits** [comment]
ok

**Comment by rdeits** [comment]
Just realized this is still open. Any objection to me merging it now?

**Comment by piever** [comment]
I'm in favor of merging now and tagging so everybody can start updating.

**Pull request merged**
