### PR TITLE
Fixed @get! deprecation warning

### PR DESCRIPTION
**Pull request by rasmushenningsson**
Tiny changes to remove deprecation warning for Base.@get!().

### CODE REVIEW

**Comment by rasmushenningsson** [comment]
The CI errors are unrelated to my fix, as far as I can tell.

**Comment by shashi** [comment]
thanks!

**Comment by thchr** [comment]
Would it be possible to do a minor-version release that includes this fix (to quiet the associated warning printouts)?

**Comment by MasonProtter** [comment]
bump. I would also appreciate a minor release

**Pull request merged**
