### PR TITLE
fix webio compat

### PR DESCRIPTION
**Pull request by SimonDanisch**
Tests don't run locally, so this is pretty annoying to maintain:
```
┌ Info: Installing NPM dependencies...
└   cmd = `'C:\Users\sdani\.julia\artifacts\0bd56198ac47b98572257a7725d9425f5a1ba1a9\npm.cmd' -C 'C:\Users\sdani\WebIODev\dev\WebIO\packages' install --scripts-prepend-node-path=auto --unsafe-perm`
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sdani\AppData\Roaming\npm-cache\_logs\2021-06-30T11_51_37_831Z-debug.log
Build JavaScript: Error During Test at C:\Users\sdani\WebIODev\dev\WebIO\test\bundling.jl:4
  Got exception outside of a @test
```
Any help appreciated

### CODE REVIEW

**Comment by samuelkim314** [comment]
Just curious if there are updates on this? I just ran into compatibility issues with PlotlyJS and GLMakie in the same environment, and it seems to be locked up by WebIO.

**Comment by SimonDanisch** [comment]
Yeah, I can't get the tests to run and CI isn't working, so there is now way for me to merge this..
@shashi @travigd will need to help with this.

**Comment by SimonDanisch** [comment]
@shashi @travigd it seems like nobody can maintain WebIO anymore...
Would it make sense to signal that, and help people move to e.g. JSServe?

**Comment by travigd** [comment]
Did this in #465 (had to upgrade some TypeScript things as well)

**Pull request closed without merging**
