### PR TITLE
more updates to make importing WebIO possible on 0.7

### PR DESCRIPTION
**Pull request by rdeits**
(this is a PR against the branch from #145 )

With these changes, I can do `using WebIO, Mux` on Julia v0.7-beta with no deprecation warnings. It still doesn't actually *work*, but at least we're getting closer.

### CODE REVIEW

**Comment by rdeits** [comment]
The most immediate issue (breaking both Mux and Blink with WebIO) is https://github.com/JuliaWeb/Mux.jl/issues/63

**Comment by piever** [comment]
Can you checkout [Mux#64](https://github.com/JuliaWeb/Mux.jl/pull/64) and [WebSockets#100](https://github.com/JuliaWeb/WebSockets.jl/pull/100) and try again here? I don't think it fixes it completely but at least you don't get a method error.

**Comment by rdeits** [comment]
Yup, definitely progress. I no longer get the MethodError, but when trying to serve a simple WebIO+Mux example, I get an `Internal Error` printed in the browser: 

```julia
julia> webio_serve(page("/", req -> Node(:div, "hello world")), 8001)
```

going to `localhost:8001` in the browser shows: 

```
StackOverflowError:
Stacktrace:
 [1] resize! at ./array.jl:814 [inlined]
 [2] ensureroom(::Base.GenericIOBuffer{Array{UInt8,1}}, ::UInt64) at ./iobuffer.jl:298
 [3] unsafe_write(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Ptr{UInt8}, ::UInt64) at ./iobuffer.jl:387
 [4] unsafe_write at ./io.jl:512 [inlined]
 [5] write at ./io.jl:581 [inlined]
 [6] print at ./show.jl:158 [inlined]
 [7] print at ./multimedia.jl:21 [inlined]
 [8] #print_to_string#336(::Nothing, ::Function, ::MIME{Symbol("text/html")}) at ./strings/io.jl:124
 [9] print_to_string at ./strings/io.jl:112 [inlined]
 [10] string at ./strings/io.jl:143 [inlined]
 [11] istextmime(::MIME{Symbol("text/html")}) at ./multimedia.jl:151
 [12] #stringmime#6 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Base64/src/Base64.jl:40 [inlined]
 [13] stringmime at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Base64/src/Base64.jl:40 [inlined]
 [14] HTTP.Messages.Response(::String) at /home/rdeits/.julia/dev/Mux/src/basics.jl:48 (repeats 79992 times)
```

**Comment by piever** [comment]
I get the same, any idea what that is about?

**Comment by rdeits** [comment]
This line: https://github.com/JuliaWeb/Mux.jl/blob/edd4c67f8b3c90152c94327a36d08164525f1ef7/src/basics.jl#L48 is just calling itself over and over

**Comment by piever** [comment]
Isn't that code a massive type piracy to HTTP?

**Comment by rdeits** [comment]
Uh, yeah. That's definitely not good.

**Comment by piever** [comment]
I can try to fix it as well in my Mux PR.

**Comment by piever** [comment]
Fixed that on my branch, but I got:

```
MethodError: no method matching (::getfield(Main, Symbol("##5#6")))(::getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}, ::Dict{Any,Any})
Closest candidates are:
  #5(::Any) at REPL[4]:1
Stacktrace:
 [1] (::getfield(Mux, Symbol("##1#2")){getfield(Main, Symbol("##5#6")),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}})(::Dict{Any,Any}) at /home/pietro/.julia/dev/Mux/src/Mux.jl:11
 [2] #5 at /home/pietro/.julia/dev/Mux/src/Mux.jl:18 [inlined]
 [3] (::getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##40#43")){Bool,getfield(Mux, Symbol("#absdir#42")){Array{String,1}}},getfield(Mux, Symbol("##41#44")){getfield(Mux, Symbol("#absdir#42")){Array{String,1}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Main, Symbol("##5#6")),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}})(::Dict{Any,Any}) at /home/pietro/.julia/dev/Mux/src/Mux.jl:11
 [4] #5 at /home/pietro/.julia/dev/Mux/src/Mux.jl:18 [inlined]
 [5] #1 at /home/pietro/.julia/dev/Mux/src/Mux.jl:11 [inlined]
 [6] toresponse(::getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##45#48")){Bool,getfield(Mux, Symbol("#absdir#47"))},getfield(Mux, Symbol("##46#49")){getfield(Mux, Symbol("#absdir#47"))}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##40#43")){Bool,getfield(Mux, Symbol("#absdir#42")){Array{String,1}}},getfield(Mux, Symbol("##41#44")){getfield(Mux, Symbol("#absdir#42")){Array{String,1}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Main, Symbol("##5#6")),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}}}, ::Dict{Any,Any}) at /home/pietro/.julia/dev/Mux/src/basics.jl:50
 [7] #1 at /home/pietro/.julia/dev/Mux/src/Mux.jl:11 [inlined]
 [8] splitquery(::getfield(Mux, Symbol("##1#2")){typeof(Mux.toresponse),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##45#48")){Bool,getfield(Mux, Symbol("#absdir#47"))},getfield(Mux, Symbol("##46#49")){getfield(Mux, Symbol("#absdir#47"))}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##40#43")){Bool,getfield(Mux, Symbol("#absdir#42")){Array{String,1}}},getfield(Mux, Symbol("##41#44")){getfield(Mux, Symbol("#absdir#42")){Array{String,1}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Main, Symbol("##5#6")),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}}}}, ::Dict{Any,Any}) at /home/pietro/.julia/dev/Mux/src/basics.jl:32
 [9] #1 at /home/pietro/.julia/dev/Mux/src/Mux.jl:11 [inlined]
 [10] basiccatch(::getfield(Mux, Symbol("##1#2")){typeof(Mux.splitquery),getfield(Mux, Symbol("##1#2")){typeof(Mux.toresponse),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##45#48")){Bool,getfield(Mux, Symbol("#absdir#47"))},getfield(Mux, Symbol("##46#49")){getfield(Mux, Symbol("#absdir#47"))}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##40#43")){Bool,getfield(Mux, Symbol("#absdir#42")){Array{String,1}}},getfield(Mux, Symbol("##41#44")){getfield(Mux, Symbol("#absdir#42")){Array{String,1}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Main, Symbol("##5#6")),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}}}}}, ::Dict{Any,Any}) at /home/pietro/.julia/dev/Mux/src/basics.jl:81
 [11] #1 at /home/pietro/.julia/dev/Mux/src/Mux.jl:11 [inlined]
 [12] todict(::getfield(Mux, Symbol("##1#2")){typeof(Mux.basiccatch),getfield(Mux, Symbol("##1#2")){typeof(Mux.splitquery),getfield(Mux, Symbol("##1#2")){typeof(Mux.toresponse),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##45#48")){Bool,getfield(Mux, Symbol("#absdir#47"))},getfield(Mux, Symbol("##46#49")){getfield(Mux, Symbol("#absdir#47"))}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##40#43")){Bool,getfield(Mux, Symbol("#absdir#42")){Array{String,1}}},getfield(Mux, Symbol("##41#44")){getfield(Mux, Symbol("#absdir#42")){Array{String,1}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}},getfield(Mux, Symbol("##1#2")){getfield(Main, Symbol("##5#6")),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}}}}}}, ::HTTP.Messages.Request) at /home/pietro/.julia/dev/Mux/src/basics.jl:23
 [13] (::getfield(Mux, Symbol("##3#4")){typeof(Mux.todict),typeof(Mux.basiccatch)})(::Function, ::HTTP.Messages.Request) at /home/pietro/.julia/dev/Mux/src/Mux.jl:15 (repeats 5 times)
 [14] (::getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##3#4")){getfield(Mux, Symbol("##3#4")){getfield(Mux, Symbol("##3#4")){getfield(Mux, Symbol("##3#4")){getfield(Mux, Symbol("##3#4")){typeof(Mux.todict),typeof(Mux.basiccatch)},typeof(Mux.splitquery)},typeof(Mux.toresponse)},getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##45#48")){Bool,getfield(Mux, Symbol("#absdir#47"))},getfield(Mux, Symbol("##46#49")){getfield(Mux, Symbol("#absdir#47"))}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}}},getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##27#28")){Array{SubString{String},1}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##5#6")){getfield(Mux, Symbol("##40#43")){Bool,getfield(Mux, Symbol("#absdir#42")){Array{String,1}}},getfield(Mux, Symbol("##41#44")){getfield(Mux, Symbol("#absdir#42")){Array{String,1}}}},getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}}},getfield(Mux, Symbol("##1#2")){getfield(Main, Symbol("##5#6")),getfield(Mux, Symbol("##1#2")){getfield(Mux, Symbol("##17#18")){getfield(Mux, Symbol("##21#22")){Symbol,Int64}},getfield(Mux, Symbol("##19#20")){String}}}})(::HTTP.Messages.Request) at /home/pietro/.julia/dev/Mux/src/Mux.jl:11
 [15] (::getfield(Mux, Symbol("##7#8")){Mux.App})(::HTTP.Messages.Request) at /home/pietro/.julia/dev/Mux/src/server.jl:42
 [16] handle_request(::getfield(Mux, Symbol("##7#8")){Mux.App}, ::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /home/pietro/.julia/dev/HTTP/src/Servers.jl:525
 [17] (::getfield(WebSockets, Symbol("##27#31")){WebSockets.ServerWS{HTTP.Servers.http,HTTP.Handlers.HandlerFunction{getfield(Mux, Symbol("##7#8")){Mux.App}},WebSockets.WebsocketHandler{getfield(Mux, Symbol("##9#10")){Mux.App}}}})(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /home/pietro/.julia/dev/WebSockets/src/HTTP.jl:320
 [18] handle_stream(::getfield(WebSockets, Symbol("##27#31")){WebSockets.ServerWS{HTTP.Servers.http,HTTP.Handlers.HandlerFunction{getfield(Mux, Symbol("##7#8")){Mux.App}},WebSockets.WebsocketHandler{getfield(Mux, Symbol("##9#10")){Mux.App}}}}, ::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /home/pietro/.julia/dev/HTTP/src/Servers.jl:499
 [19] (::getfield(HTTP.Servers, Symbol("##54#55")){getfield(WebSockets, Symbol("##27#31")){WebSockets.ServerWS{HTTP.Servers.http,HTTP.Handlers.HandlerFunction{getfield(Mux, Symbol("##7#8")){Mux.App}},WebSockets.WebsocketHandler{getfield(Mux, Symbol("##9#10")){Mux.App}}}},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at ./task.jl:262
```

**Comment by piever** [comment]
I got stuck on that one, the stacktrace is very hard to read because of the many anonymous functions: let me know if you can figure out!

**Comment by rdeits** [comment]
I also looked at it and couldn't figure out what was going on. I'm currently trying to figure out why FunctionalCollections is also broken on 0.7

**Comment by piever** [comment]
What is the status of other environments (say IJulia or Juno) with this PR in Julia 0.7? It's good to know if some of them are working to see if I have an environment to start updating the various Interact*, Knockout and company.

**Pull request closed without merging**
