### PR TITLE
another try at Julia v0.7 support

### LINKED ISSUE #47: Integrate with HTTP.jl
From Slack:

> Eric Forgy [3:15 PM]
> Maybe I can help adapt it to HTTP :blush:
>
> Shashi Gowda [3:19 PM]
> A PR for that would be welcome! 
> https://github.com/JuliaGizmos/WebIO.jl/blob/master/src/providers/mux_setup.jl is how I do it in Mux. WebIO integration also generally requires that package assets be available at `/pkg/`. `/pkg/Foo/bar.js` which corresponds to the file `Foo/assets/bar.js` in Foo.jl directory.
> GitHub
> JuliaGizmos/WebIO.jl
> WebIO.jl - a DSL for web-based widgets in Julia
> I ended up adding this directly to Mux -- https://github.com/JuliaWeb/Mux.jl/pull/34
> GitHub
> Serve package asset files by shashi · Pull Request #34 · JuliaWeb/Mux.jl
> A file at MyPkg/assets/js/test.js will be served at /pkg/MyPkg/js/test.js supersedes JunoLab/Blink.jl#55

```julia
using Mux
using WebIO
webio_serve(req -> TableView.showtable(t))
```

### LINKED ISSUE #128: Getting WebIO working on v0.7
Related to:

+ https://discourse.julialang.org/t/allow-pkg-dir-on-juliabox/9784/5?u=djsegal

-----

<br>

Currently getting the following error from [this line](https://github.com/JuliaGizmos/WebIO.jl/blob/92e58d6401e94edd2d12908fe352e7d800377398/deps/build.jl#L17):

<br>

```julia
WARNING: Broadcast.broadcast_indices is deprecated, use broadcast_axes instead.
  likely near /Users/dan/.julia/packages/Nullables/sjCf/src/nullable.jl:414
WARNING: Base.Pkg is deprecated, run `using Pkg` instead
  likely near /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:36
WARNING: Base.Pkg is deprecated, run `using Pkg` instead
  likely near /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:36
┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│   caller = install_ijulia_config() at build.jl:15
└ @ Main build.jl:15
ERROR: LoadError: MethodError: no method matching dir()
Closest candidates are:
  dir(!Matched::String, !Matched::String...) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:403
Stacktrace:
 [1] install_ijulia_config() at /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:17
 [2] top-level scope
 [3] include at ./boot.jl:314 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1070
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] include(::String) at ./client.jl:390
 [7] top-level scope
in expression starting at /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:36
```

### LINKED ISSUE #164: Pkg.build"WebIO") fails, in Julia 0.7 beta2
Pkg.build("WebIO") fails with the following error:

```
 Building WebIO → `~/.julia/packages/WebIO/8IdD/deps/build.log`
┌ Error: Error building `WebIO`:
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /root/.julia/packages/WebIO/8IdD/deps/build.jl:36
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /root/.julia/packages/WebIO/8IdD/deps/build.jl:36
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /root/.julia/packages/WebIO/8IdD/deps/build.jl:36
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /root/.julia/packages/WebIO/8IdD/deps/build.jl:36
│ in install_ijulia_config at /root/.julia/packages/WebIO/8IdD/deps/build.jl
│ ┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│ │   caller = install_ijulia_config() at build.jl:15
│ └ @ Main ~/.julia/packages/WebIO/8IdD/deps/build.jl:15
│ ERROR: LoadError: MethodError: no method matching dir()
│ Closest candidates are:
│   dir(!Matched::String, !Matched::String...) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:433
│ Stacktrace:
│  [1] install_ijulia_config() at /root/.julia/packages/WebIO/8IdD/deps/build.jl:17
│  [2] top-level scope at none:0
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1034
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:393
│  [7] top-level scope at none:0
│ in expression starting at /root/.julia/packages/WebIO/8IdD/deps/build.jl:36
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:1007
```
Looking at deps/build.jl, Pkg.dir() is used, but is undefined in Julia 0.7:
```
julia> Pkg.dir()
ERROR: MethodError: no method matching dir()
Closest candidates are:
  dir(::String, ::String...) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:433
Stacktrace:
 [1] top-level scope at none:0
```
https://github.com/JuliaLang/Pkg.jl/issues/417

### LINKED ISSUE #172: Error Building WebIO in Julia 1.0.0
Building WebIO ────────→ `~/.julia/packages/WebIO/7rrhi/deps/build.log`
┌ Error: Error building `WebIO`:
│ ERROR: LoadError: MethodError: no method matching replace(::String, ::Regex, ::String)
│ Closest candidates are:
│   replace(::String, !Matched::Pair{#s55,B} where B where #s55<:AbstractChar; count) at strings/util.jl:414
│   replace(::String, !Matched::Pair{#s52,B} where B where #s52<:Union{Tuple{Vararg{AbstractChar,N} where N}, Set{#s49} where #s49<:AbstractChar, AbstractArray{#s50,1} where #s50<:AbstractChar}; count) at strings/util.jl:419
│   replace(::String, !Matched::Pair; count) at strings/util.jl:423
│   ...
│ Stacktrace:
│  [1] install_ijulia_config() at /Users/XXX/.julia/packages/WebIO/7rrhi/deps/build.jl:15
│  [2] top-level scope at none:0
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:388
│  [7] top-level scope at none:0
│ in expression starting at /Users/XXX/.julia/packages/WebIO/7rrhi/deps/build.jl:55
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

### PR DESCRIPTION
**Pull request by rdeits**
Combines #145 and #157 

Fixes #172 
Fixes #164 
Fixes #128 
Fixes #47

### CODE REVIEW

**Comment by rdeits** [comment]
All the WebIO tests except the `blink-tests.jl` file pass on v0.7 with this branch, but none of our communication actually works because the websocket support via Mux/WebSockets is still not working.

**Comment by rdeits** [comment]
Good news! With https://github.com/JuliaWeb/Mux.jl/pull/66 , HTTP.jl master, WebSockets.jl master, and the latest changes from b09b03c9e13a1163a5afb5df34e788e56be2f967 we now have working websockets in WebIO on v0.7! The clock demo and "random print button" demo from the readme are both working for me with Mux on v0.7.

**Comment by rdeits** [comment]
Blink integration also seems to work with https://github.com/JunoLab/Blink.jl/pull/139

**Comment by rdeits** [comment]
Ok, I'm going for it :)

**Comment by lewisl** [comment]
Won't build for me still:

```
 Error: Error building `WebIO`: 
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:55
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:55
│ ┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│ │   caller = install_ijulia_config() at build.jl:15
│ └ @ Main ~/.julia/packages/WebIO/RolaR/deps/build.jl:15
│ ERROR: LoadError: MethodError: no method matching dir()
│ Closest candidates are:
│   dir(!Matched::String, !Matched::AbstractString...) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:454
│ Stacktrace:
│  [1] install_ijulia_config() at /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:17
│  [2] top-level scope at none:0
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:398
│  [7] top-level scope at none:0
│ in expression starting at /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:55
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:1068
```

Looks like it is the load error for dir()

**Comment by rdeits** [comment]
@lewisl you need WebIO.jl master

**Comment by lewisl** [comment]
I never explicitly requested any particular branch.  If I didn’t get master it is because something is wrong with the build process for the package.

**Comment by shashi** [comment]
@lewisl This version was not released yet. So you got the old released
version.

>

**Comment by lewisl** [comment]
Thanks.  Master was older branch; thought it was released.  Master built and compiled.

**Pull request merged**
