### PR TITLE
Fix frontend test

### LINKED ISSUE #499: Tests fail locally
I cloned the repository and ran the tests, but they fail. This makes it hard to make a contribution :(

```
➜  ~ julia18x86
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0 (2022-08-17)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.8) pkg> activate --temp
  Activating new project at `/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_oZ6tvQ`

(jl_oZ6tvQ) pkg> dev /Users/fons/Documents/WebIO.jl/
   Resolving package versions...
    Updating `/private/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_oZ6tvQ/Project.toml`
  [0f1e0344] + WebIO v0.8.18 `~/Documents/WebIO.jl`
    Updating `/private/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_oZ6tvQ/Manifest.toml`
  [bf4720bc] + AssetRegistry v0.1.0
  [3da002f7] + ColorTypes v0.11.4
  [5ae59095] + Colors v0.12.8
  [53c48c17] + FixedPointNumbers v0.8.4
  [de31a74c] + FunctionalCollections v0.5.0
⌅ [cd3eb016] + HTTP v0.9.17
  [83e8ac13] + IniFile v0.5.1
  [682c06a0] + JSON v0.21.3
  [739be429] + MbedTLS v1.1.7
  [510215fc] + Observables v0.5.2
  [bac558e1] + OrderedCollections v1.4.1
  [69de0a69] + Parsers v2.4.2
  [fa939f87] + Pidfile v1.3.0
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.3.0
  [5c2747f8] + URIs v1.4.0
  [0f1e0344] + WebIO v0.8.18 `~/Documents/WebIO.jl`
  [104b5d7c] + WebSockets v1.5.9
  [cc8bc4a8] + Widgets v0.6.6
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL v0.6.3
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.8.0
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [fa267f1f] + TOML v1.0.0
  [a4e569a6] + Tar v1.10.0
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v0.5.2+0
  [deac9b47] + LibCURL_jll v7.84.0+0
  [29816b5a] + LibSSH2_jll v1.10.2+0
  [c8ffd9c3] + MbedTLS_jll v2.28.0+0
  [14a3606d] + MozillaCACerts_jll v2022.2.1
  [4536629a] + OpenBLAS_jll v0.3.20+0
  [83775a58] + Zlib_jll v1.2.12+3
  [8e850b90] + libblastrampoline_jll v5.1.1+0
  [8e850ede] + nghttp2_jll v1.48.0+0
  [3f19e933] + p7zip_jll v17.4.0+0
        Info Packages marked with ⌅ have new versions available but cannot be upgraded. To see why use `status --outdated -m`

(jl_oZ6tvQ) pkg> test WebIO
     Testing WebIO
      Status `/private/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_v2uiIe/Project.toml`
  [bf4720bc] AssetRegistry v0.1.0
  [ad839575] Blink v0.12.5
  [8f4d0f93] Conda v1.7.0
  [864edb3b] DataStructures v0.18.13
  [de31a74c] FunctionalCollections v0.5.0
  [7073ff75] IJulia v1.23.3
  [97c1335a] JSExpr v0.5.4
  [682c06a0] JSON v0.21.3
⌅ [a975b10e] Mux v0.7.6
  [0db19996] NBInclude v2.3.0
  [510215fc] Observables v0.5.2
  [ae029012] Requires v1.3.0
  [0f1e0344] WebIO v0.8.18 `~/Documents/WebIO.jl`
  [104b5d7c] WebSockets v1.5.9
  [cc8bc4a8] Widgets v0.6.6
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [56ddb016] Logging `@stdlib/Logging`
  [44cfe95a] Pkg v1.8.0 `@stdlib/Pkg`
  [9a3f8284] Random `@stdlib/Random`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
      Status `/private/var/folders/v_/fhpj9jn151d4p9c2fdw2gv780000gn/T/jl_v2uiIe/Manifest.toml`
  [bf4720bc] AssetRegistry v0.1.0
  [9e28174c] BinDeps v1.0.2
  [ad839575] Blink v0.12.5
  [3da002f7] ColorTypes v0.11.4
  [5ae59095] Colors v0.12.8
  [34da2185] Compat v4.3.0
  [8f4d0f93] Conda v1.7.0
  [9a962f9c] DataAPI v1.12.0
  [864edb3b] DataStructures v0.18.13
  [e2d170a0] DataValueInterfaces v1.0.0
  [53c48c17] FixedPointNumbers v0.8.4
  [de31a74c] FunctionalCollections v0.5.0
⌅ [cd3eb016] HTTP v0.9.17
  [9fb69e20] Hiccup v0.2.2
  [7073ff75] IJulia v1.23.3
  [83e8ac13] IniFile v0.5.1
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.4.1
  [97c1335a] JSExpr v0.5.4
  [682c06a0] JSON v0.21.3
  [50d2b5c4] Lazy v0.15.1
  [1914dd2f] MacroTools v0.5.10
  [739be429] MbedTLS v1.1.7
  [ffc61752] Mustache v1.0.14
⌅ [a975b10e] Mux v0.7.6
  [0db19996] NBInclude v2.3.0
  [510215fc] Observables v0.5.2
  [bac558e1] OrderedCollections v1.4.1
  [69de0a69] Parsers v2.4.2
  [fa939f87] Pidfile v1.3.0
  [21216c6a] Preferences v1.3.0
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [b85f4697] SoftGlobalScope v1.1.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.10.0
  [30578b45] URIParser v0.4.1
  [5c2747f8] URIs v1.4.0
  [81def892] VersionParsing v1.3.0
  [0f1e0344] WebIO v0.8.18 `~/Documents/WebIO.jl`
  [104b5d7c] WebSockets v1.5.9
  [cc8bc4a8] Widgets v0.6.6
  [c2297ded] ZMQ v1.2.2
  [8f1865be] ZeroMQ_jll v4.3.4+0
  [a9144af2] libsodium_jll v1.0.20+0
  [0dad84c5] ArgTools v1.1.1 `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads v1.6.0 `@stdlib/Downloads`
  [7b1f6079] FileWatching `@stdlib/FileWatching`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL v0.6.3 `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions v1.2.0 `@stdlib/NetworkOptions`
  [44cfe95a] Pkg v1.8.0 `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA v0.7.0 `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML v1.0.0 `@stdlib/TOML`
  [a4e569a6] Tar v1.10.0 `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll v0.5.2+0 `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll v7.84.0+0 `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll v1.10.2+0 `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll v2.28.0+0 `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll v2022.2.1 `@stdlib/MozillaCACerts_jll`
  [4536629a] OpenBLAS_jll v0.3.20+0 `@stdlib/OpenBLAS_jll`
  [83775a58] Zlib_jll v1.2.12+3 `@stdlib/Zlib_jll`
  [8e850b90] libblastrampoline_jll v5.1.1+0 `@stdlib/libblastrampoline_jll`
  [8e850ede] nghttp2_jll v1.48.0+0 `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll v17.4.0+0 `@stdlib/p7zip_jll`
        Info Packages marked with ⌅ have new versions available but cannot be upgraded.
Precompiling project...
  36 dependencies successfully precompiled in 14 seconds. 15 already precompiled.
     Testing Running tests...
┌ Info: Installing NPM dependencies...
└   cmd = `npm -C /Users/fons/Documents/WebIO.jl/packages install --scripts-prepend-node-path=auto --unsafe-perm`

up to date, audited 1231 packages in 1s

69 packages are looking for funding
  run `npm fund` for details

39 vulnerabilities (3 moderate, 36 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
┌ Info: Building packages...
└   cmd = `npm -C /Users/fons/Documents/WebIO.jl/packages run build-prod --scripts-prepend-node-path=auto --unsafe-perm --`

> build-prod
> lerna run build-prod

lerna notice cli v3.22.1
lerna info Executing command in 4 packages: "npm run build-prod"
lerna ERR! npm run build-prod exited 2 in '@webio/webio'
lerna ERR! npm run build-prod stdout:

> @webio/webio@0.8.15 build-prod
> npm run build && webpack -p


> @webio/webio@0.8.15 build
> tsc -p . && webpack

Hash: 244c379e1fd63993874b
Version: webpack 4.46.0
Time: 328ms
Built at: 02-11-2022 13:07:55
              Asset      Size  Chunks                   Chunk Names
    webio.bundle.js  7.16 KiB   webio  [emitted]        webio
webio.bundle.js.map  3.96 KiB   webio  [emitted] [dev]  webio
Entrypoint webio = webio.bundle.js webio.bundle.js.map
[0] multi index.ts 28 bytes {webio} [built]
[./index.ts] 2.82 KiB {webio} [built] [failed] [1 error]

ERROR in ./index.ts
Module build failed (from /Users/fons/Documents/WebIO.jl/packages/node_modules/ts-loader/index.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:43193:18)
    at /Users/fons/Documents/WebIO.jl/packages/node_modules/ts-loader/dist/servicesHost.js:244:56
    at /Users/fons/Documents/WebIO.jl/packages/node_modules/ts-loader/dist/servicesHost.js:87:142
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/fons/Documents/WebIO.jl/packages/node_modules/ts-loader/dist/servicesHost.js:87:125)
    at actualResolveTypeReferenceDirectiveNamesWorker (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:118257:163)
    at resolveTypeReferenceDirectiveNamesWorker (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:118557:26)
    at processTypeReferenceDirectives (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:120054:31)
    at findSourceFileWorker (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:119939:21)
    at findSourceFile (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:119791:26)
    at /Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:119740:85
    at getSourceFileFromReferenceWorker (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:119706:34)
    at processSourceFile (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:119740:13)
    at processTypeReferenceDirectiveWorker (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:120104:25)
    at processTypeReferenceDirective (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:120070:13)
    at Object.createProgram (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:118360:21)
    at synchronizeHostData (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:167688:26)
    at Object.getProgram (/Users/fons/Documents/WebIO.jl/packages/node_modules/typescript/lib/typescript.js:167802:13)
    at successfulTypeScriptInstance (/Users/fons/Documents/WebIO.jl/packages/node_modules/ts-loader/dist/instances.js:171:80)
    at Object.getTypeScriptInstance (/Users/fons/Documents/WebIO.jl/packages/node_modules/ts-loader/dist/instances.js:34:12)
    at Object.loader (/Users/fons/Documents/WebIO.jl/packages/node_modules/ts-loader/dist/index.js:17:41)
 @ multi index.ts webio[0]

lerna ERR! npm run build-prod exited 2 in '@webio/webio'
Build JavaScript: Error During Test at /Users/fons/Documents/WebIO.jl/test/bundling.jl:4
  Got exception outside of a @test
  LoadError: failed process: Process(`npm -C /Users/fons/Documents/WebIO.jl/packages run build-prod --scripts-prepend-node-path=auto --unsafe-perm --`, ProcessExited(2)) [2]
  
  Stacktrace:
    [1] pipeline_error
      @ ./process.jl:565 [inlined]
    [2] run(::Cmd; wait::Bool)
      @ Base ./process.jl:480
    [3] run(::Cmd)
      @ Base ./process.jl:477
    [4] top-level scope
      @ ~/Documents/WebIO.jl/deps/_bundlejs.jl:26
    [5] include(mod::Module, _path::String)
      @ Base ./Base.jl:419
    [6] include
      @ ~/Documents/WebIO.jl/src/WebIO.jl:1 [inlined]
    [7] bundlejs()
      @ WebIO ~/Documents/WebIO.jl/src/devsetup.jl:6
    [8] macro expansion
      @ ~/Documents/WebIO.jl/test/bundling.jl:9 [inlined]
    [9] macro expansion
      @ /Applications/Julia-1.8 x86.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Test/src/Test.jl:1357 [inlined]
   [10] top-level scope
      @ ~/Documents/WebIO.jl/test/bundling.jl:5
   [11] include(fname::String)
      @ Base.MainInclude ./client.jl:476
   [12] top-level scope
      @ ~/Documents/WebIO.jl/test/runtests.jl:7
   [13] include(fname::String)
      @ Base.MainInclude ./client.jl:476
   [14] top-level scope
      @ none:6
   [15] eval
      @ ./boot.jl:368 [inlined]
   [16] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:276
   [17] _start()
      @ Base ./client.jl:522
  in expression starting at /Users/fons/Documents/WebIO.jl/deps/_bundlejs.jl:8
Test Summary:    | Error  Total  Time
Build JavaScript |     1      1  7.2s
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/fons/Documents/WebIO.jl/test/bundling.jl:4
in expression starting at /Users/fons/Documents/WebIO.jl/test/runtests.jl:7
ERROR: Package WebIO errored during testing

(jl_oZ6tvQ) pkg> 

julia> versioninfo()
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, westmere)
  Threads: 1 on 8 virtual cores

```

Tested on Julia 1.8 arm64 and Julia 1.8 x86 on MacOS

### PR DESCRIPTION
**Pull request by olegshtch**
Updates webpack to fix work on new nodejs.

### CODE REVIEW

**Comment by mind6** [comment]
So this should now be merged with #500?

**Comment by olegshtch** [comment]
I suppose this PR should be merged before to get clean CI.

**Comment by MasonProtter** [comment]
These changes aren't compatible with Observables v0.4, so we need to drop compatibility with it and only support v0.5. Also, `Observables.listeners` is used in two additional places here that need updating. I've proposed these changes as a PR to your PR branch here: https://github.com/olegshtch/WebIO.jl/pull/1

**Comment by halleysfifthinc** [comment]
This is great! I think we should probably keep the various PR's separate as much as possible. Are the changes for Observable listeners necessary to get tests passing again?

**Comment by olegshtch** [comment]
@halleysfifthinc No, Observable listeners don't related to tests. Sounds reasonable, I've removed additional commits.

**Comment by MasonProtter** [comment]
Those commits about listeners are required to fix InteractBase.jl for me. Is the idea here to do those changes in #497?

**Comment by halleysfifthinc** [comment]
My thought was to keep PRs separate and as small as possible, which is often preferred by maintainers (but I don't know for WebIO maintainers). I'm equally invested in getting #497 merged (along with #498) to fix PlotlyJS plot updates in Jupyter.

**Comment by halleysfifthinc** [comment]
In case there was any confusion, my suggestion was to reduce the scope of this PR to solely fix the frontend tests, and remove both mine and @MasonProtter s contributions for fixing #497 from this PR. Multiple currently open PRs (#500, #497, #498) would benefit from having the master branch passing tests again.

The reduced scope could be a quicker/easier merge.

**Comment by olegshtch** [comment]
Removed all commits not related to frontend.

**Comment by fonsp** [comment]
Does someone understand the test failures? Is it related to this PR?

**Comment by olegshtch** [comment]
@fonsp Yes, this PR fixes test failure in `bundling.jl`

**Comment by halleysfifthinc** [comment]
The remaining test failures are unrelated to bundling and are solved by #497.

**Comment by MasonProtter** [comment]
Seems really weird to me to split up the fixes into two separate PRs, since now we have two PRs where the tests don't pass rather than one PR where all tests pass.

**Comment by MasonProtter** [comment]
Regardless, @pfitzseb or @timholy could someone merge this? This and #497 are ready and if taken together get all the tests passing

**Comment by MasonProtter** [comment]
Thanks @pfitzseb, would you mind triggering the JuliaRegistrator? @fonsp added me to the repo but I'm not allowed to commit or trigger the registrator.

**Pull request merged**
