### PR TITLE
move widget methods from InteractBase

### PR DESCRIPTION
**Pull request by piever**
I'm moving methods from AbstractWidget here from InteractBase, so that it's easier to keep things in sync when the integration with other packages changes.

### CODE REVIEW

**Comment by piever** [comment]
This fails tests but I think it was failing already?

**Comment by rdeits** [comment]
Yeah, the tests need the Blink and JSExpr PRs in order to pass. Sorry--it's hard to update when there are circular tests dependencies like this

**Comment by piever** [comment]
I see, can I merge this one then? It's completely orthogonal, passes tests locally and I needed for the Interact update.

**Comment by rdeits** [comment]
Yeah, that's fine

**Pull request merged**
