### PR TITLE
remove wrong normpath, allow to customize bundle url

### LINKED ISSUE #221: master URL problems
I tried to get the webio integration back to work for [nextjournal](https://nextjournal.com/) and WebIO#master... Works nicely with @pfitzseb fix, but it somehow ignores the correct bundle script url in the show, and tries to load the bundle from some other url - from somewhere I can't figure out.

So this is the warning:
```
Loading failed for the <script> with source “https://nextjournal.com/nextjournal.com/runner/17592187153510/runtime/35be8c6e-5910-49fe-9371-25b3c82af96a/assetserver/938b6762b7760d5a822833867808fe726c56e52b-generic-http.js”. in  edit:2:1
```
Note the repeated host `nextjournal.com/`... 
The `edit` file the stack trace links to isn't really helpful and I have no idea where to look in there :D I already tried searching in it for http.js etc, but couldn't even find it.

The html that gets displayed looks correct though:
```html
<head>
    <script>window._webIOWebSocketURL = "wss://nextjournal.com/runner/17592187153510/runtime/35be8c6e-5910-49fe-9371-25b3c82af96a/webio_websocket/";</script>
    <script src="https:/nextjournal.com/runner/17592187153510/runtime/35be8c6e-5910-49fe-9371-25b3c82af96a/assetserver/938b6762b7760d5a822833867808fe726c56e52b-generic-http.js"></script>
</head>
<body>
    <div class="webio-mountpoint" data-webio-mountpoint="17684436027718352057">
        <strong>WebIO not detected.</strong>
    </div>
</body>
```
So, where else does the bundle get loaded, and why does it append the host 2 times?

cc @travigd

### PR DESCRIPTION
**Pull request by SimonDanisch**
fix #221

### CODE REVIEW

**Comment by shashi** [comment]
:trophy:

**Comment by shashi** [comment]
It should be easy to add tests to this if you wanted to. You can basically bring up a server and load the URL in blink, access the insides of the window and check if it loaded. (see blink_tests.jl)

**Comment by SimonDanisch** [comment]
thanks to @pfitzseb for noticing the missing `/` :)

**Comment by SimonDanisch** [comment]
Yay :) 
grafik
@pfitzseb do you want to make sure, that I don't mess up atom? I for some reason don't have atom and webio running correctly right now^^

**Comment by pfitzseb** [comment]
Seems to work fine in Juno, afaict.

**Comment by SimonDanisch** [comment]
Weird, travis is all green, but shows still as yellow... ¯\_(ツ)_/¯

**Pull request merged**
