### PR TITLE
WIP: IFrame wrapper

### PR DESCRIPTION
**Pull request by shashi**
Can be used to fight pre-existing stylesheets and event handlers.

cc @rdeits 

I'm now trying to get the height to be the same as content (doesn't work when content < 150px). ~Another issue is observables don't sync between the parent and the frame (e.g. slider)~

### CODE REVIEW

**Comment by rdeits** [comment]
This is awesome, thank you! I'll try it out right away.

**Comment by rdeits** [comment]
I'm getting syntax errors in Firefox from the `javascript:void()` `src` attribute. It seems to work anyway, but the errors go away if I change that to `javascript:void(0)`

**Comment by shashi** [comment]
Okay we should use that then!

**Comment by rdeits** [comment]
Ok, this is working great for rendering my content. Thank you! The only missing piece is the ability to send observables from Julia into the iframe. I'm still trying to figure out how that would work.

**Comment by shashi** [comment]
You mean just using Observables in Scope that is wrapped in `iframe`?

Doesn't that work?

I can do

```julia
In[1]: s = slider(1:10)
In[2]: iframe(s)
In[3]: WebIO.render(observe(s))
```
and both sliders update the observable...

**Comment by rdeits** [comment]
Is that `slider()` from InteractNext.jl? I'll give it a shot. 

Sorry, what I meant was that I tried pushing updates from Julia to JS using the clock demo from the readme:

```julia
w = Scope()
obs = Observable(w, "clock-value", "")

timestr() = Dates.format(now(), "HH:MM:SS")

# update timestamp every second
@async while true
    sleep(1)
    obs[] = timestr()
end

# on every update to `obs`, replace the text content of #clock
onjs(obs, @js val -> begin
    console.log(val);
    @var clock = this.dom.querySelector("#clock")
    clock.textContent = val
end)

WebIO.iframe(w(
  dom"div#clock"(
    timestr(),
  ),
))
```

but the resulting clock doesn't update. Is that expected?

**Comment by shashi** [comment]
Oh I see. No we should definitely fix that before merging this. I'll have a look.

**Comment by rdeits** [comment]
Ok, thank you!

**Comment by shashi** [comment]
Just pushed the required fixes. Clock works, and sliders also sync :-)

**Comment by rdeits** [comment]
Yup, confirmed that it works for MeshCat.jl too!

**Pull request merged**
